sudo: required
services:
  - docker
before_install:
  - docker build -t alvarogonzavega/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true alvarogonzavega/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-680371135686"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $access_key_id
  secret_access_key: $secret_access_key  
